### PR TITLE
Fixed broken u of a license image

### LINKED ISSUE #1676: [Discovery] U of a logo license image broken
**Describe the bug**
Image for 'licensed for u of a' of the u of a logo is broken. The src on the image is '//s3.amazonaws.com/libapps/sites/165/icons/6665/ualib-logo.png' which I believe is a poorly formed URL that should be 'https://libapps-ca.s3.amazonaws.com/sites/165/icons/6665/ualib-logo.png'

**To Reproduce**
1. Make a search
2. Click on library in left sidebar
3. Click on 'University of Alberta Internet' facet
4. Notice that every item has a broken image where the u of a logo should appear

**Screenshots**
Screenshot from 2019-06-12 13-13-56

**Additional context**

It was discussed below that brand guidlines specify that the U of A shield must be accompanied by text. Natasha has provided a shield with text here:

https://user-images.githubusercontent.com/495318/59459963-3d75df00-8ddb-11e9-8a02-9f41e8ca8cd4.png

that could be stored in app/assets/images and used for both the U of A holdings icon and the database icon.

### PR DESCRIPTION
**Pull request by ConnorSheremeta**
- Fixed image by using a local stored image
- Replaced database shield icon with locally stored icon

Fixes #1676

Before:
Screenshot from 2019-08-12 12-15-01
Screenshot from 2019-08-12 12-14-56
Screenshot from 2019-08-12 12-14-34
After:
Screenshot from 2019-08-12 12-13-21
Screenshot from 2019-08-12 12-12-53
Screenshot from 2019-08-12 12-12-45

### CODE REVIEW

**Comment by weiweishi** [comment]
See some tests are broken?
```
  1) Search results UofA holdings logo Search results have logo if UofA holding
     [31mFailure/Error: [0m[32mexpect[0m(element).to have_css([31m[1;31m"[0m[31mimg[src*='ualib-logo.png'][1;31m"[0m[31m[0m)[0m
     [31m  expected to find visible css "img[src*='ualib-logo.png']" within #<Capybara::Node::Element tag="div" path="/html/body/div[1]/div[5]/div[2]/div[3]/div[2]/div[2]/div[3]/div[1]"> but there were no matches[0m
     [36m# ./spec/features/search_uofa_holdings_logo_spec.rb:16:in `block (3 levels) in <top (required)>'[0m
     [36m# ./spec/features/search_uofa_holdings_logo_spec.rb:15:in `block (2 levels) in <top (required)>'[0m

  2) Search results UofA holdings logo Search results have logo if a holding is from both UofA and another location
     [31mFailure/Error: [0m[32mexpect[0m(element).to have_css([31m[1;31m"[0m[31mimg[src*='ualib-logo.png'][1;31m"[0m[31m[0m)[0m
     [31m  expected to find visible css "img[src*='ualib-logo.png']" within #<Capybara::Node::Element tag="div" path="/html/body/div[1]/div[5]/div[2]/div[3]/div[2]/div[2]/div[3]/div[1]"> but there were no matches[0m
     [36m# ./spec/features/search_uofa_holdings_logo_spec.rb:52:in `block (3 levels) in <top (required)>'[0m
     [36m# ./spec/features/search_uofa_holdings_logo_spec.rb:51:in `block (2 levels) in <top (required)>'[0m
```

File: app/helpers/catalog_helper.rb [hunk 1]
```diff
@@ -68,6 +68,11 @@ def libguides_icons(document)
   end
 
   def libguide_icon_image(icon)
-    "https://libapps-ca.s3.amazonaws.com/sites/#{icon[:site_id]}/icons/#{icon[:id]}/#{icon[:file]}"
+    # If icon is u of a shield, use our asset which has text next to it
+    if icon[:id] == '6665'
```
Comment (weiweishi) [inline app/helpers/catalog_helper.rb]: I know this ticket is to fix the broken icon specifically but wondering if we can identify other icons that are from springshare, and maybe capture them in a separate issue to fix them soon?
I don't know if there's a better way to identify icons that need to be rendered, than relying on an ID that is based on an external system. This could change on LibGuides easily? But there might not be other means to do it right now - maybe something we need to investigate further in the future.

File: app/views/catalog/_index_default.html.erb [hunk 2]
```diff
@@ -27,7 +27,7 @@
           <% end %>
         <% end.empty? -%>
           <% if display_ual_shield document and (document.to_h["source_tesim"] and document.to_h["source_tesim"].first == "Symphony")%>
-            <img alt="licensed for U of A" title="licensed for U of A" src="//s3.amazonaws.com/libapps/sites/165/icons/6665/ualib-logo.png" style="height:18px" />
+            <img alt="licensed for U of A" title="licensed for U of A" src=<%= asset_path("ualib-logo-green.png") %> style="height:18px" />
```
Comment (weiweishi) [inline app/views/catalog/_index_default.html.erb]: Is there any way to not do the in-line style? I know Shane has always spoken against it, and I'd be curious to see if there's a better way to use CSS to define the style needed for the shields?

File: app/helpers/catalog_helper.rb (hunk 1 above)
Comment (ConnorSheremeta) [reply app/helpers/catalog_helper.rb]: Yes it would be much nicer if the icon provided from the lib guide already contained the text. A change in icon id would break this. Would you recommend leaving the database icons as-is in this ticket and opening another one to investigate changing the lib guide icon?

Comment (weiweishi) [reply app/helpers/catalog_helper.rb]: Yes. we are limited sometimes to be optimal. For your question, depending on the amount of work? if there are icons you already know the ids, and can fold into the work then I'd say adding them in, but if more investigations are needed to find all icons used in Discovery, or to track down the correct versions of the image etc. I'd say opening a separate ticket and deal with them later.
